# Generated by Django 3.0 on 2022-07-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(help_text='логин', verbose_name='Логин')),
            ],
            options={
                'verbose_name': 'Логин',
                'verbose_name_plural': 'Логины',
                'ordering': ['-id'],
            },
        ),
    ]
